routes/web.php
<?php

/*
	|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(array('prefix'=>'/'), function(){
	Route::get('/', 'PengusulController@getIndex')->name('pengusul_index');

	Route::get('register', 'PengusulController@getRegister')->name('pengusul_register');
	Route::post('register', 'PengusulController@postRegister')->name('pengusul_register_post');
	Route::get('login', 'PengusulController@getLogin')->name('pengusul_login');
	Route::post('login', 'PengusulController@postLogin')->name('pengusul_login_post');
	Route::get('logout', 'PengusulController@getLogout')->name('pengusul_logout');

	// Beranda
	Route::get('beranda', 'PengusulController@getBeranda')->name('pengusul_beranda');
	Route::post('edit-biodata', 'PengusulController@postEditBiodata');

	// Berita
	Route::get('berita', 'PengusulController@getBerita');
	Route::get('berita/{id}', 'PengusulController@getDetailBerita');

	// Daftar Pengajuan
	Route::get('pengajuan', 'PengusulController@getPengajuan')->name('pengusul_pengajuan');

	// Desain Industri
	Route::get('pengajuan-industri', 'PengusulController@getPengajuanDesainIndustri')->name('pengusul_desain_industri_pengajuan');
	Route::post('pengajuan-industri', 'PengusulController@postPengajuanDesainIndustri')->name('pengusul_desain_industri_pengajuan_post');
	Route::get('pengajuan-industri/{id}', 'PengusulController@getDetailDesainIndustri')->name('pengusul_desain_industri_detail');
	Route::get('edit-pengajuan-industri/{id}', 'PengusulController@getEditDesainIndustri');
	Route::post('edit-pengajuan-industri', 'PengusulController@postEditDesainIndustri');

	// Paten
	Route::get('pengajuan-paten', 'PengusulController@getPengajuanPaten')->name('pengusul_paten_pengajuan');
	Route::get('pengajuan-paten/{id}', 'PengusulController@getDetailPaten')->name('pengusul_desain_industri_detail');
	Route::post('pengajuan-paten', 'PengusulController@postPengajuanPaten')->name('pengusul_paten_pengajuan_post');
	Route::get('edit-pengajuan-paten/{id}', 'PengusulController@getEditPaten');
	Route::post('edit-pengajuan-paten', 'PengusulController@postEditPaten');

	// Hak Cipta
	Route::get('pengajuan-hak-cipta', 'PengusulController@getPengajuanHakCipta')->name('pengusul_hak_cipta_pengajuan');
	Route::post('pengajuan-hak-cipta', 'PengusulController@postPengajuanHakCipta')->name('pengusul_pengajuan_hak_cipta_pengajuan_post');
	Route::get('pengajuan-hak-cipta/{id}', 'PengusulController@getDetailHakCipta');
	Route::get('edit-pengajuan-hak-cipta/{id}', 'PengusulController@getEditHakCipta');
	Route::post('edit-pengajuan-hak-cipta', 'PengusulController@postEditHakCipta');

	// Merek
	Route::get('pengajuan-merek', 'PengusulController@getPengajuanMerek')->name('pengusul_merek_pengajuan');
	Route::post('pengajuan-merek', 'PengusulController@postPengajuanMerek')->name('pengusul_merek_pengajuan_post');
	Route::get('pengajuan-merek/{id}', 'PengusulController@getDetailMerek');
	Route::get('edit-pengajuan-merek/{id}', 'PengusulController@getEditMerek');
	Route::post('edit-pengajuan-merek', 'PengusulController@postEditMerek');

	Route::post('delete-pengajuan', 'PengusulController@postDeletePengajuan');
	
});

Route::group(array('prefix'=>'download'), function(){
	// Download File Paten
	Route::get('paten/surat-kuasa/{filename}', 'DownloadController@getPatenSuratKuasa');
	Route::get('paten/surat-pengalihan-hak-penemuan/{filename}', 'DownloadController@getPatenSuratPengalihanHakPenemuan');
	Route::get('paten/surat-kepemilikan-inventor/{filename}', 'DownloadController@getPatenSuratKepemilikanInventor');
	Route::get('paten/surat-pernyataan-invensi-oleh-lembaga/{filename}', 'DownloadController@getPatenSuratkepemilikanLembaga');
	Route::get('paten/dokumen-terjemahan/{filename}', 'DownloadController@getPatenDokumenTerjemahan');

	Route::get('paten/dokumen-subtantif-deskripsi/{filename}', 'DownloadController@getPatenDokumenSubtantifDeskripsi');
	Route::get('paten/dokumen-subtantif-gambar/{filename}', 'DownloadController@getPatenDokumenSubtantifGambar');

	// Download File Desain Industri
	Route::get('desain-industri/surat-kuasa/{filename}', 'DownloadController@getDesainIndustriSuratKuasa');
	Route::get('desain-industri/surat-pengalihan-hak/{filename}', 'DownloadController@getDesainIndustriSuratPernyataanPengalihanHak');
	Route::get('desain-industri/bukti-pemilikan-hak/{filename}', 'DownloadController@getDesainIndustriBuktiPemilikanHak');
	Route::get('desain-industri/bukti-prioritas-terjemahan/{filename}', 'DownloadController@getDesainIndustriBuktiPrioritasTerjemahan');
	Route::get('desain-industri/dokumen/{filename}', 'DownloadController@getDesainIndustriDokumenDesainIndustri');
	Route::get('desain-industri/uraian/{filename}', 'DownloadController@getDesainIndustriUraian');
	Route::get('desain-industri/gambar/{filename}', 'DownloadController@getDesainIndustriGambarDesainIndustri');

	// Download File Merek
	Route::get('merek/etiket-merek/{filename}', 'DownloadController@getMerekEtiketMerek');
});

Route::group(array('prefix'=>'cetak'), function(){
	Route::get('paten/{id}', 'GenerateFileController@getFilePaten');
	Route::get('desain-industri/{id}', 'GenerateFileController@getFileDesainIndustri');
	Route::get('hak-cipta/{id}', 'GenerateFileController@getFileHakCipta');
	Route::get('merek/{id}', 'GenerateFileController@getFileMerek');
});


// Route list for admin by herusetiawan

Route::get('administrator', function () {
    return redirect()->route('admin.getLogin');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::get('login', 'AuthController@showLogin')->name('getLogin');
    Route::post('login', 'AuthController@postLogin')->name('postLogin');
    Route::get('logout', 'AuthController@getLogout')->name('getLogout');

    Route::group(['middleware' => 'auth:web'], function () {
	   
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('paten', 'PatenController', ['except' => ['create', 'store']]);
        Route::resource('desainindustri', 'DesainIndustriController', ['except' => ['create', 'store']]);
        Route::resource('hakcipta', 'HakCiptaController', ['except' => ['create', 'store']]);
        Route::resource('merek', 'MerekController', ['except' => ['create', 'store']]);
        Route::resource('berita', 'BeritaController');
        Route::resource('pengusul', 'PengusulController', ['except' => ['create', 'store', 'edit', 'update', 'show']]);
        Route::resource('admin', 'AdminController', ['except' => ['edit', 'update', 'show']]);
	});
});

resources/views/admin/home.blade.php
@extends('layouts.adminLayout')

@section('content')
  <div class="content-header">
    <h3>Beranda</h3>
  </div>
  <div class="content body">
    <div class="row">
      <div class="col-sm-4">
        <div class="small-box bg-yellow">
          <div class="inner">
            <h3>10</h3>
            <p>Permintaan HAKI Baru</p>
          </div>
          <div class="icon">
            <i class="fa fa-file"></i>
          </div>
          <a href="#" class="small-box-footer">
             Info Selanjutnya <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="small-box bg-green">
          <div class="inner">
            <h3>30</h3>
            <p>HAKI telah terivikasi</p>
          </div>
          <div class="icon">
            <i class="fa fa-check"></i>
          </div>
          <a href="#" class="small-box-footer">
             Info Selanjutnya <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="small-box bg-aqua">
          <div class="inner">
            <h3>20</h3>
            <p>Konsultan HAKI</p>
          </div>
          <div class="icon">
            <i class="fa fa-user"></i>
          </div>
          <a href="#" class="small-box-footer">
            Info Selanjutnya <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
      </div>
    </div>

    {{-- Box Statistik --}}
    <div class="row">
      <div class="col-sm-6">
        <div class="box box-primary">
          <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-paper-plane"></i> Pengajuan Usulan HAKI Baru</h3>
          </div>
            <ul class="nav nav-stacked">
              <li><a href="#">Scantour <span class="pull-right badge bg-orange"><i class="fa fa-close"></i> Belum terverifikasi</span></a></li>
              <li><a href="#">GOku: GO <span class="pull-right badge bg-orange"><i class="fa fa-close"></i> Belum terverifikasi</span></a></li>
              <li><a href="#">Math Eater <span class="pull-right badge bg-orange"><i class="fa fa-close"></i> Belum terverifikasi</span></a></li>
            </ul>
          <div class="box-footer">
            <a href="#" class="btn btn-primary pull-right">Lihat Semua</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="box box-warning">
          <div class="box-header with-border">
            <h3 class="box-title"><i class="fa fa-pie-chart"></i> Statistik Perbandingan Pengajuan</h3>
          </div>
          <div class="box-body">
            <canvas id="pieChart" style="height:250px"></canvas>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('js')
  <script src="{{asset('/admin/plugins/chartjs/Chart.min.js')}}" charset="utf-8"></script>
  <script type="text/javascript">
    var pieChartCanvas = $("#pieChart").get(0).getContext("2d");
    var pieChart = new Chart(pieChartCanvas);
    var PieData = [
      {
        value: 5,
        color: "#f56954",
        highlight: "#f56954",
        label: "Desain Industri"
      },
      {
        value: 10,
        color: "#00a65a",
        highlight: "#00a65a",
        label: "Hak Paten"
      }
    ];
    var pieOptions = {
      //Boolean - Whether we should show a stroke on each segment
      segmentShowStroke: true,
      //String - The colour of each segment stroke
      segmentStrokeColor: "#fff",
      //Number - The width of each segment stroke
      segmentStrokeWidth: 2,
      //Number - The percentage of the chart that we cut out of the middle
      percentageInnerCutout: 50, // This is 0 for Pie charts
      //Number - Amount of animation steps
      animationSteps: 100,
      //String - Animation easing effect
      animationEasing: "easeOutBounce",
      //Boolean - Whether we animate the rotation of the Doughnut
      animateRotate: true,
      //Boolean - Whether we animate scaling the Doughnut from the centre
      animateScale: false,
      //Boolean - whether to make the chart responsive to window resizing
      responsive: true,
      // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
      maintainAspectRatio: true,
      //String - A legend template
      // legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>"
    };
    //Create pie or douhnut chart
    // You can switch between pie and douhnut using the method below.
    pieChart.Pie(PieData, pieOptions);

  </script>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin | IPON UNY</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{{ asset('/admin/bootstrap/css/bootstrap.min.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{{ asset('/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('/admin/dist/css/AdminLTE.min.css') }}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('/admin/dist/css/skins/_all-skins.min.css') }}">
  <link rel="stylesheet" href="{{ asset('/css/toastr.min.css') }}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#">ADMIN IPON UNY</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Masuk sebagai Administrator</p>

    <form action="{{ route('admin.postLogin') }}" method="post">
      <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="Email" name="email" value="{{  old('email') }}" required>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="password" required>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">

        <!-- /.col -->
        <div class="col-xs-4">
          {{csrf_field()}}
          <button type="submit" class="btn btn-primary btn-block btn-flat">Login</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.0 -->
<script src="../../plugins/jQuery/jQuery-2.2.0.min.js"></script>
<!-- Bootstrap 3.3.6 -->
<script src="../../bootstrap/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' // optional
    });
  });
</script>
</body>
</html>