routes/web.php
<?php

/*
	|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(array('prefix'=>'/'), function(){
	Route::get('/', 'PengusulController@getIndex')->name('pengusul_index');

	Route::get('register', 'PengusulController@getRegister')->name('pengusul_register');
	Route::post('register', 'PengusulController@postRegister')->name('pengusul_register_post');
	Route::get('login', 'PengusulController@getLogin')->name('pengusul_login');
	Route::post('login', 'PengusulController@postLogin')->name('pengusul_login_post');
	Route::get('logout', 'PengusulController@getLogout')->name('pengusul_logout');

	// Beranda
	Route::get('beranda', 'PengusulController@getBeranda')->name('pengusul_beranda');
	Route::post('edit-biodata', 'PengusulController@postEditBiodata');

	// Berita
	Route::get('berita', 'PengusulController@getBerita');
	Route::get('berita/{id}', 'PengusulController@getDetailBerita');

	// Daftar Pengajuan
	Route::get('pengajuan', 'PengusulController@getPengajuan')->name('pengusul_pengajuan');

	// Desain Industri
	Route::get('pengajuan-industri', 'PengusulController@getPengajuanDesainIndustri')->name('pengusul_desain_industri_pengajuan');
	Route::post('pengajuan-industri', 'PengusulController@postPengajuanDesainIndustri')->name('pengusul_desain_industri_pengajuan_post');
	Route::get('pengajuan-industri/{id}', 'PengusulController@getDetailDesainIndustri')->name('pengusul_desain_industri_detail');
	Route::get('edit-pengajuan-industri/{id}', 'PengusulController@getEditDesainIndustri');
	Route::post('edit-pengajuan-industri', 'PengusulController@postEditDesainIndustri');

	// Paten
	Route::get('pengajuan-paten', 'PengusulController@getPengajuanPaten')->name('pengusul_paten_pengajuan');
	Route::get('pengajuan-paten/{id}', 'PengusulController@getDetailPaten')->name('pengusul_desain_industri_detail');
	Route::post('pengajuan-paten', 'PengusulController@postPengajuanPaten')->name('pengusul_paten_pengajuan_post');
	Route::get('edit-pengajuan-paten/{id}', 'PengusulController@getEditPaten');
	Route::post('edit-pengajuan-paten', 'PengusulController@postEditPaten');

	// Hak Cipta
	Route::get('pengajuan-hak-cipta', 'PengusulController@getPengajuanHakCipta')->name('pengusul_hak_cipta_pengajuan');
	Route::post('pengajuan-hak-cipta', 'PengusulController@postPengajuanHakCipta')->name('pengusul_pengajuan_hak_cipta_pengajuan_post');
	Route::get('pengajuan-hak-cipta/{id}', 'PengusulController@getDetailHakCipta');
	Route::get('edit-pengajuan-hak-cipta/{id}', 'PengusulController@getEditHakCipta');
	Route::post('edit-pengajuan-hak-cipta', 'PengusulController@postEditHakCipta');

	// Merek
	Route::get('pengajuan-merek', 'PengusulController@getPengajuanMerek')->name('pengusul_merek_pengajuan');
	Route::post('pengajuan-merek', 'PengusulController@postPengajuanMerek')->name('pengusul_merek_pengajuan_post');
	Route::get('pengajuan-merek/{id}', 'PengusulController@getDetailMerek');
	Route::get('edit-pengajuan-merek/{id}', 'PengusulController@getEditMerek');
	Route::post('edit-pengajuan-merek', 'PengusulController@postEditMerek');

	Route::post('delete-pengajuan', 'PengusulController@postDeletePengajuan');
	
});

Route::group(array('prefix'=>'download'), function(){
	// Download File Paten
	Route::get('paten/surat-kuasa/{filename}', 'DownloadController@getPatenSuratKuasa');
	Route::get('paten/surat-pengalihan-hak-penemuan/{filename}', 'DownloadController@getPatenSuratPengalihanHakPenemuan');
	Route::get('paten/surat-kepemilikan-inventor/{filename}', 'DownloadController@getPatenSuratKepemilikanInventor');
	Route::get('paten/surat-pernyataan-invensi-oleh-lembaga/{filename}', 'DownloadController@getPatenSuratkepemilikanLembaga');
	Route::get('paten/dokumen-terjemahan/{filename}', 'DownloadController@getPatenDokumenTerjemahan');

	Route::get('paten/dokumen-subtantif-deskripsi/{filename}', 'DownloadController@getPatenDokumenSubtantifDeskripsi');
	Route::get('paten/dokumen-subtantif-gambar/{filename}', 'DownloadController@getPatenDokumenSubtantifGambar');

	// Download File Desain Industri
	Route::get('desain-industri/surat-kuasa/{filename}', 'DownloadController@getDesainIndustriSuratKuasa');
	Route::get('desain-industri/surat-pengalihan-hak/{filename}', 'DownloadController@getDesainIndustriSuratPernyataanPengalihanHak');
	Route::get('desain-industri/bukti-pemilikan-hak/{filename}', 'DownloadController@getDesainIndustriBuktiPemilikanHak');
	Route::get('desain-industri/bukti-prioritas-terjemahan/{filename}', 'DownloadController@getDesainIndustriBuktiPrioritasTerjemahan');
	Route::get('desain-industri/dokumen/{filename}', 'DownloadController@getDesainIndustriDokumenDesainIndustri');
	Route::get('desain-industri/uraian/{filename}', 'DownloadController@getDesainIndustriUraian');
	Route::get('desain-industri/gambar/{filename}', 'DownloadController@getDesainIndustriGambarDesainIndustri');

	// Download File Merek
	Route::get('merek/etiket-merek/{filename}', 'DownloadController@getMerekEtiketMerek');
});

Route::group(array('prefix'=>'cetak'), function(){
	Route::get('paten/{id}', 'GenerateFileController@getFilePaten');
	Route::get('desain-industri/{id}', 'GenerateFileController@getFileDesainIndustri');
	Route::get('hak-cipta/{id}', 'GenerateFileController@getFileHakCipta');
	Route::get('merek/{id}', 'GenerateFileController@getFileMerek');
});


// Route list for admin by herusetiawan

Route::get('administrator', function () {
    return redirect()->route('admin.getLogin');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::get('login', 'AuthController@showLogin')->name('getLogin');
    Route::post('login', 'AuthController@postLogin')->name('postLogin');
    Route::get('logout', 'AuthController@getLogout')->name('getLogout');

    Route::group(['middleware' => 'auth:web'], function () {
	   
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('paten', 'PatenController', ['except' => ['create', 'store']]);
        Route::resource('desainindustri', 'DesainIndustriController', ['except' => ['create', 'store']]);
        Route::resource('hakcipta', 'HakCiptaController', ['except' => ['create', 'store']]);
        Route::resource('merek', 'MerekController', ['except' => ['create', 'store']]);
        Route::resource('berita', 'BeritaController');
        Route::resource('pengusul', 'PengusulController', ['except' => ['create', 'store', 'edit', 'update', 'show']]);
        Route::resource('admin', 'AdminController', ['except' => ['edit', 'update', 'show']]);
	});
});

app/HakCipta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HakCipta extends Model
{
	protected $table = 'hak_cipta';

	protected $fillable = ['biodata_id', 'nama_ciptaan', 'pencipta_nama', 'pencipta_kewarganegaraan', 'pencipta_alamat', 'pemegang_hak_cipta_nama', 'pemegang_hak_cipta_kewarganegaraan', 'pemegang_hak_cipta_alamat', 'kuasa_nama', 'kuasa_kewarganegaraan', 'kuasa_alamat', 'jenis_hak_cipta_id', 'tanggal_diumumkan', 'tempat_diumumkan', 'uraian_ciptaan', 'status', 'reviewer_id'];
	
	public function jenis_hak_cipta(){
		return $this->belongsTo('App\JenisHakCipta');
	}

    public function biodata(){
    	return $this->belongsTo('App\Biodata');
    }
}

app/Http/Controllers/Admin/HakCiptaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\HakCipta;

class HakCiptaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hakciptas = DB::table('hak_cipta')
                    ->select('hak_cipta.*', 'biodata.nama')
                    ->join('biodata', 'hak_cipta.biodata_id', '=', 'biodata.id')
                    ->orderBy('id', 'DESC')
                    ->get();

        return view('admin.hakcipta.index')
                ->with('hakciptas', $hakciptas);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $hakcipta = HakCipta::with('biodata')
                        ->with('jenis_hak_cipta')
                        ->where('id', $id)
                        ->firstOrFail();

        return view('admin.hakcipta.detail')
                    ->with('hakcipta', $hakcipta);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $input['status'] = '1';
        $data = HakCipta::find($id);
        $data->update($input);

        return redirect()->route('admin.hakcipta.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        HakCipta::destroy($id);

        return redirect()->route('admin.hakcipta.index'); 
    }
}

resources/views/admin/hakcipta/detail.blade.php
@extends('layouts.adminLayout')

@section('content')
  <div class="content-header">
    {{-- <h3 class="title">Detail Pengajuan : {{$data->judul_invensi}} <small class="label bg-green pull-right"><i class="fa fa-check"></i> Terverifikasi</small></h3> --}}
      @if($hakcipta->status == 1)
        <h3 class="title">Detail Pengajuan Hak Cipta : {{$hakcipta->nama_ciptaan}} <small class="label label-success pull-right"><i class="fa fa-check"></i> Pengajuan Diterima</small></h3>
      @elseif($hakcipta->status == 0)
        <h3 class="title">Detail Pengajuan Hak Cipta : {{$hakcipta->nama_ciptaan}} <small class="label label-warning pull-right"><i class="fa fa-close"></i> Proses Pengajuan</small></h3>
      @endif
  </div>
  <div class="content">

    {{--  Boox Data Diri --}}
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Data Diri Pengaju</h3>
      </div>
      <div class="box-body">
        <div class="row form-group">
          <label class="col-sm-2 control-label">
            Nama :
          </label>
          <div class="col-sm-10">
            <p>{{ $hakcipta->biodata->nama }}</p>
          </div>
          <label class="col-sm-2 control-label">
            Alamat :
          </label>
          <div class="col-sm-10">
            <p>{{ $hakcipta->biodata->alamat }}</p>
          </div>
          <label class="col-sm-2 control-label">
            Kewarganegaraan :
          </label>
          <div class="col-sm-10">
            <p>{{ $hakcipta->biodata->kewarganegaraan }}</p>
          </div>
          <label class="col-sm-2 control-label">
            Telepon :
          </label>
          <div class="col-sm-10">
            <p>{{ $hakcipta->biodata->no_hp }}</p>
          </div>
          <label class="col-sm-2 control-label">
            Email :
          </label>
          <div class="col-sm-10">
            <p>{{ $hakcipta->biodata->email }}</p>
          </div>
          <label class="col-sm-2 control-label">
            NPWP :
          </label>
          <div class="col-sm-10">
            @if($hakcipta->biodata->npwp==NULL)
            <p>-</p>
            @else
            <p>{{ $hakcipta->biodata->npwp }}</p>
            @endif
          </div>
          <label class="col-sm-2 control-label">
            Nomor Permohonan :
          </label>
          <div class="col-sm-10">
            <p>{{ $hakcipta->id }}</p>
          </div>
        </div>
      </div>
    </div>

    {{-- Box Data Pengajuan --}}
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Data Hak Cipta</h3>
        </div>
        <div class="box-body">
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Judul Ciptaan :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->nama_ciptaan}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Jenis Ciptaan :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->jenis_hak_cipta->nama_jenis_hak_cipta}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Uraian Ciptaan :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->uraian_ciptaan}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Tempat pertama kali diumumkan :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->tempat_diumumkan}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Tanggal pertama kali diumumkan :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->tanggal_diumumkan}}</p>
            </div>
          </div>
        </div>
      </div>

      {{-- Box data Pencipta --}}
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Data Pencipta</h3>
        </div>
        <div class="box-body">
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Nama :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->pencipta_nama}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Kewarganegaraan :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->pencipta_kewarganegaraan}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Alamat :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->pencipta_alamat}}</p>
            </div>
          </div>
        </div>
      </div>

      {{-- Box Data Pemegang Hak Cipta --}}
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Data Pemegang Hak Cipta</h3>
        </div>
        <div class="box-body">
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Nama :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->pemegang_hak_cipta_nama}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Kewarganegaraan :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->pemegang_hak_cipta_kewarganegaraan}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Alamat :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->pemegang_hak_cipta_alamat}}</p>
            </div>
          </div>
        </div>
      </div>

      {{-- Box Data Kuasa --}}
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Data Kuasa</h3>
        </div>
        <div class="box-body">
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Nama :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->kuasa_nama}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Kewarganegaraan :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->kuasa_kewarganegaraan}}</p>
            </div>
          </div>
          <div class="row form-group">
            <label class="col-sm-2 control-label">
              Alamat :
            </label>
            <div class="col-sm-10">
              <p>{{$hakcipta->kuasa_alamat}}</p>
            </div>
          </div>
        </div>
      </div>

    {{-- Box Validasi --}}
    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title">Verifikasi</h3>
      </div>
      <div class="box-body">
        <p>Cek kembali kelengkapan data dan lampiran pengajuan Hak Paten. Jika data sudah lengkap dan benar, silahkan klik tombol verifikasi</p>
        <a href="{{ route('admin.hakcipta.edit', $hakcipta->id) }}" class="btn btn-success"><i class="fa fa-check"></i> Verifikasi</a>
      </div>
    </div>

  {{-- End of Content --}}
  </div>


@endsection

resources/views/admin/hakcipta/index.blade.php
@extends('layouts.adminLayout')

@section('header')
  <link rel="stylesheet" href="{{ asset('/css/dataTables.bootstrap.min.css') }}" media="screen" title="no title">
@endsection

@section('content')
  <div class="content-header">
    <h3>Pengajuan Hak Cipta</h3>
  </div>
  <div class="content body">
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-success">
          <!-- <div class="box-header">
            test
          </div> -->
          <div class="box-body">
            <table id="tableindustri" class="table table-bordered">
              <thead>
                <tr>
                  <th>No.</th>
                  <th>Judul</th>
                  <th>Nama Pengaju</th>
                  <th>Status</th>
                  <th colspan="2">Aksi</th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 1; ?>
                @foreach($hakciptas as $hakcipta)
                  <tr>
                    <td>{{ $i++ }}</td>
                    <td>{{ $hakcipta->nama_ciptaan }}</td>
                    <td>{{ $hakcipta->nama }}</td>
                    <td>
                      @if($hakcipta->status == 1)
                          <label class="label label-success">Diterima</label> 
                        @else
                          <label class="label label-warning">Proses</label> 
                        @endif
                    </td>
                    <td>
                      <a data-id="1" href="{{Route('admin.hakcipta.show', $hakcipta->id)}}" class="btn-view btn bg-green"><i class="fa fa-eye"></i></a>
                      </td>
                    <td>
                      {{ Form::model($hakcipta, ['route' => ['admin.hakcipta.destroy', $hakcipta->id], 'method'=>'DELETE', 'class' => 'form-inline', 'id' => 'form-hapus-'.$i]) }}
                      <a href="#" class="btn-delete btn bg-red" onclick="confirmHapus('{{ $i }}','{{ $hakcipta->nama_ciptaan }}')"><i class="fa fa-trash"></i></a>
                      {{ Form::close() }}
                    </td>
                  </tr>
                @endforeach
                </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

@section('js')
  <script src="{{ asset('/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('/js/bootbox.min.js') }}"></script>
  <script type="text/javascript">
    $('#tableindustri').dataTable();

    function confirmHapus(id,data) {
    // return false;
    bootbox.confirm("Hapus Hak Cipta '" + data + "' ?", function(result) {
      if(result) {
        document.getElementById('form-hapus-'+id).submit();
      }
    });         
  }
  </script>
@endsection