routes/web.php
<?php

/*
	|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::group(array('prefix'=>'/'), function(){
	Route::get('/', 'PengusulController@getIndex')->name('pengusul_index');

	Route::get('register', 'PengusulController@getRegister')->name('pengusul_register');
	Route::post('register', 'PengusulController@postRegister')->name('pengusul_register_post');
	Route::get('login', 'PengusulController@getLogin')->name('pengusul_login');
	Route::post('login', 'PengusulController@postLogin')->name('pengusul_login_post');
	Route::get('logout', 'PengusulController@getLogout')->name('pengusul_logout');

	// Beranda
	Route::get('beranda', 'PengusulController@getBeranda')->name('pengusul_beranda');
	Route::post('edit-biodata', 'PengusulController@postEditBiodata');

	// Berita
	Route::get('berita', 'PengusulController@getBerita');
	Route::get('berita/{id}', 'PengusulController@getDetailBerita');

	// Daftar Pengajuan
	Route::get('pengajuan', 'PengusulController@getPengajuan')->name('pengusul_pengajuan');

	// Desain Industri
	Route::get('pengajuan-industri', 'PengusulController@getPengajuanDesainIndustri')->name('pengusul_desain_industri_pengajuan');
	Route::post('pengajuan-industri', 'PengusulController@postPengajuanDesainIndustri')->name('pengusul_desain_industri_pengajuan_post');
	Route::get('pengajuan-industri/{id}', 'PengusulController@getDetailDesainIndustri')->name('pengusul_desain_industri_detail');
	Route::get('edit-pengajuan-industri/{id}', 'PengusulController@getEditDesainIndustri');
	Route::post('edit-pengajuan-industri', 'PengusulController@postEditDesainIndustri');

	// Paten
	Route::get('pengajuan-paten', 'PengusulController@getPengajuanPaten')->name('pengusul_paten_pengajuan');
	Route::get('pengajuan-paten/{id}', 'PengusulController@getDetailPaten')->name('pengusul_desain_industri_detail');
	Route::post('pengajuan-paten', 'PengusulController@postPengajuanPaten')->name('pengusul_paten_pengajuan_post');
	Route::get('edit-pengajuan-paten/{id}', 'PengusulController@getEditPaten');
	Route::post('edit-pengajuan-paten', 'PengusulController@postEditPaten');

	// Hak Cipta
	Route::get('pengajuan-hak-cipta', 'PengusulController@getPengajuanHakCipta')->name('pengusul_hak_cipta_pengajuan');
	Route::post('pengajuan-hak-cipta', 'PengusulController@postPengajuanHakCipta')->name('pengusul_pengajuan_hak_cipta_pengajuan_post');
	Route::get('pengajuan-hak-cipta/{id}', 'PengusulController@getDetailHakCipta');
	Route::get('edit-pengajuan-hak-cipta/{id}', 'PengusulController@getEditHakCipta');
	Route::post('edit-pengajuan-hak-cipta', 'PengusulController@postEditHakCipta');

	// Merek
	Route::get('pengajuan-merek', 'PengusulController@getPengajuanMerek')->name('pengusul_merek_pengajuan');
	Route::post('pengajuan-merek', 'PengusulController@postPengajuanMerek')->name('pengusul_merek_pengajuan_post');
	Route::get('pengajuan-merek/{id}', 'PengusulController@getDetailMerek');
	Route::get('edit-pengajuan-merek/{id}', 'PengusulController@getEditMerek');
	Route::post('edit-pengajuan-merek', 'PengusulController@postEditMerek');

	Route::post('delete-pengajuan', 'PengusulController@postDeletePengajuan');
	
});

Route::group(array('prefix'=>'download'), function(){
	// Download File Paten
	Route::get('paten/surat-kuasa/{filename}', 'DownloadController@getPatenSuratKuasa');
	Route::get('paten/surat-pengalihan-hak-penemuan/{filename}', 'DownloadController@getPatenSuratPengalihanHakPenemuan');
	Route::get('paten/surat-kepemilikan-inventor/{filename}', 'DownloadController@getPatenSuratKepemilikanInventor');
	Route::get('paten/surat-pernyataan-invensi-oleh-lembaga/{filename}', 'DownloadController@getPatenSuratkepemilikanLembaga');
	Route::get('paten/dokumen-terjemahan/{filename}', 'DownloadController@getPatenDokumenTerjemahan');

	Route::get('paten/dokumen-subtantif-deskripsi/{filename}', 'DownloadController@getPatenDokumenSubtantifDeskripsi');
	Route::get('paten/dokumen-subtantif-gambar/{filename}', 'DownloadController@getPatenDokumenSubtantifGambar');

	// Download File Desain Industri
	Route::get('desain-industri/surat-kuasa/{filename}', 'DownloadController@getDesainIndustriSuratKuasa');
	Route::get('desain-industri/surat-pengalihan-hak/{filename}', 'DownloadController@getDesainIndustriSuratPernyataanPengalihanHak');
	Route::get('desain-industri/bukti-pemilikan-hak/{filename}', 'DownloadController@getDesainIndustriBuktiPemilikanHak');
	Route::get('desain-industri/bukti-prioritas-terjemahan/{filename}', 'DownloadController@getDesainIndustriBuktiPrioritasTerjemahan');
	Route::get('desain-industri/dokumen/{filename}', 'DownloadController@getDesainIndustriDokumenDesainIndustri');
	Route::get('desain-industri/uraian/{filename}', 'DownloadController@getDesainIndustriUraian');
	Route::get('desain-industri/gambar/{filename}', 'DownloadController@getDesainIndustriGambarDesainIndustri');

	// Download File Merek
	Route::get('merek/etiket-merek/{filename}', 'DownloadController@getMerekEtiketMerek');
});

Route::group(array('prefix'=>'cetak'), function(){
	Route::get('paten/{id}', 'GenerateFileController@getFilePaten');
	Route::get('desain-industri/{id}', 'GenerateFileController@getFileDesainIndustri');
	Route::get('hak-cipta/{id}', 'GenerateFileController@getFileHakCipta');
	Route::get('merek/{id}', 'GenerateFileController@getFileMerek');
});


// Route list for admin by herusetiawan

Route::get('administrator', function () {
    return redirect()->route('admin.getLogin');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function () {
    Route::get('login', 'AuthController@showLogin')->name('getLogin');
    Route::post('login', 'AuthController@postLogin')->name('postLogin');
    Route::get('logout', 'AuthController@getLogout')->name('getLogout');

    Route::group(['middleware' => 'auth:web'], function () {
	   
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('paten', 'PatenController', ['except' => ['create', 'store']]);
        Route::resource('desainindustri', 'DesainIndustriController', ['except' => ['create', 'store']]);
        Route::resource('hakcipta', 'HakCiptaController', ['except' => ['create', 'store']]);
        Route::resource('merek', 'MerekController', ['except' => ['create', 'store']]);
        Route::resource('berita', 'BeritaController');
        Route::resource('pengusul', 'PengusulController', ['except' => ['create', 'store', 'edit', 'update', 'show']]);
        Route::resource('admin', 'AdminController', ['except' => ['edit', 'update', 'show']]);
	});
});

app/Berita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Berita extends Model
{
    protected $table = 'berita';

    protected $fillable = ['judul_berita', 'isi_berita', 'foto'];
}

app/Http/Controllers/Admin/BeritaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Berita;
use File;

class BeritaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $beritas = Berita::all();

        return view('admin.berita.index')
                ->with('beritas', $beritas);
    }


    public function create()
    {
        return view('admin.berita.create');
    }

    public function store(Request $request)
    {
        $input = $request->all();

        $path = public_path('foto_berita/');

        $file = $request->file('foto');
        $file->move($path, $file->getClientOriginalName());
        $input['foto'] = $file->getClientOriginalName();
        
        Berita::create($input);

        return redirect()->route('admin.berita.index')
            ->with('successMessage', 'Berhasil Menambahkan Data Baru'); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $berita = Berita::findOrFail($id);

        return view('admin.berita.edit')
                ->with('berita', $berita);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();

        $input['foto'] = $request->input('foto_lama');

        if($request->hasFile('foto')){
            $path = public_path('foto_berita/');

            $file = $request->file('foto');
            $file->move($path, $file->getClientOriginalName());
            $input['foto'] = $file->getClientOriginalName();
        }

        $data = Berita::find($id);
        $data->update($input);

        return redirect()->route('admin.berita.index')
            ->with('successMessage', 'Berhasil Mengedit Data'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Berita::destroy($id);

        return redirect()->route('admin.berita.index'); 
    }
}

resources/views/admin/berita/create.blade.php
@extends('layouts.adminLayout')

@section('content')
  <div class="content-header">
    
  </div>
  <div class="content">

    {{--  Boox Data Diri --}}
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Tambah Berita</h3>
      </div>
      <div class="box-body">
        
      {{ Form::open(array('route' => 'admin.berita.store', 'class' => 'form-horizontal', 'method' => 'POST', 'id' => 'frm', 'enctype' => 'multipart/form-data')) }}
       <div class="modal-body">
        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-left" for="form-field-1-1"> Judul Berita : </label>
          <div class="col-sm-9">
            <input autofocus type="text" name="judul_berita" placeholder="Judul Berita" class="form-control" required  />
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-left" for="form-field-1-1"> Isi Berita : </label>
          <div class="col-sm-9">
            <textarea name="isi_berita" cols="30" rows="10" required class="form-control" placeholder="Isi Berita"></textarea>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-left" for="form-field-1-1"> Foto : </label>
          <div class="col-sm-9">
            <input type="file" name="foto" class="form-control" required  />
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn btn-sm btn-primary" type="submit">
          <i class="ace-icon fa fa-save"></i>
          Simpan
        </button>
        <a href="{{ route('admin.berita.index') }}">
        <button class="btn btn-sm btn-danger pull-right" type="button">
          <i class="ace-icon fa fa-times"></i>
          Kembali
        </button>
        </a>
      </div>
      {{ Form::close() }}

      </div>
    </div>

  {{-- End of Content --}}
  </div>


@endsection

resources/views/admin/berita/detail.blade.php
@extends('layouts.adminLayout')

@section('content')
  <div class="content-header">
    {{-- <h3 class="title">Detail Pengajuan : {{$data->judul_invensi}} <small class="label bg-green pull-right"><i class="fa fa-check"></i> Terverifikasi</small></h3> --}}
      @if($paten->status == 1)
        <h3 class="title">Detail Pengajuan Paten : {{$paten->judul_invensi}} <small class="label label-success pull-right"><i class="fa fa-check"></i> Pengajuan Diterima</small></h3>
      @elseif($paten->status == 0)
        <h3 class="title">Detail Pengajuan Paten : {{$paten->judul_invensi}} <small class="label label-warning pull-right"><i class="fa fa-close"></i> Proses Pengajuan</small></h3>
      @endif
  </div>
  <div class="content">

    {{--  Boox Data Diri --}}
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Data Diri Pengaju</h3>
      </div>
      <div class="box-body">
        <div class="row form-group">
          <label class="col-sm-2 control-label">
            Nama :
          </label>
          <div class="col-sm-10">
            <p>{{ $paten->biodata->nama }}</p>
          </div>
          <label class="col-sm-2 control-label">
            Alamat :
          </label>
          <div class="col-sm-10">
            <p>{{ $paten->biodata->alamat }}</p>
          </div>
          <label class="col-sm-2 control-label">
            Kewarganegaraan :
          </label>
          <div class="col-sm-10">
            <p>{{ $paten->biodata->kewarganegaraan }}</p>
          </div>
          <label class="col-sm-2 control-label">
            Telepon :
          </label>
          <div class="col-sm-10">
            <p>{{ $paten->biodata->no_hp }}</p>
          </div>
          <label class="col-sm-2 control-label">
            Email :
          </label>
          <div class="col-sm-10">
            <p>{{ $paten->biodata->email }}</p>
          </div>
          <label class="col-sm-2 control-label">
            NPWP :
          </label>
          <div class="col-sm-10">
            @if($paten->biodata->npwp==NULL)
            <p>-</p>
            @else
            <p>{{ $paten->biodata->npwp }}</p>
            @endif
          </div>
          <label class="col-sm-2 control-label">
            Nomor Permohonan :
          </label>
          <div class="col-sm-10">
            <p>{{ $paten->id }}</p>
          </div>
        </div>
      </div>
    </div>

    {{-- Box Data Pengajuan --}}
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Data Paten</h3>
      </div>
      <div class="box-body">
        <div class="row form-group">
          <label class="col-sm-2 control-label">
            Judul Invensi :
          </label>
          <div class="col-sm-10">
            <p>{{ $paten->judul_invensi }}</p>
          </div>
        </div>
        <div class="row form-group">
          <label class="col-sm-2 control-label">
            Jenis Paten :
          </label>
          <div class="col-sm-10">
            @if($paten->jenis_paten=='paten')
            <p>Paten</p>
            @else
            <p>Paten Sederhana</p>
            @endif
          </div>
        </div>
        @if($paten->paten_pecahan_nomor != null)
        <div class="row form-group">
          <label class="col-sm-2 control-label">
            Nomor Pecahan Paten :
          </label>
          <div class="col-sm-10">
            <p>{{ $paten->paten_pecahan_nomor }}</p>
          </div>
        </div>
        @endif

        @if($paten->konsultan != null)
        <div class="row form-group">
          <label class="col-sm-2 control-label">
            Konsultan Haki :
          </label>
          <div class="col-sm-10">
            <p>{{$paten->konsultan}}</p>
          </div>
        </div>
        @endif

        <div class="row form-group">
          <label class="col-sm-2 control-label">
            Inventor :
          </label>
          <div class="col-sm-10">
            @foreach($paten->inventor as $inventor)
            <p>{{ $inventor->nama.' - '.$inventor->kewarganegaraan }}</p>
            @endforeach
          </div>
        </div>

        <div class="row form-group">
          <label class="col-xs-2 control-label">Pengajuan dengan hak prioritas? :</label>
          <div class="col-xs-10">
            @if($paten->hak_prioritas_id==NULL)
              <p>Tidak</p>
            @else
              <p>Ya</p>
            @endif
          </div>
        </div>
        <div class="row form-group">
          <div class="row" id="form-prioritas">

          </div>
        </div>
      </div>
    </div>
    {{-- Box Lampiran --}}

    <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Lampiran Dokumen Formatif</h3>
        </div>
        <div class="box-body">
          <div class="row form-group">
            <label class="col-sm-3">Surat kuasa</label>
            <div class="col-sm-9">
              @if($paten->surat_kuasa != null)
                <a href="/download/paten/surat-kuasa/{{$paten->surat_kuasa}}" class="btn btn-success"  target='_blank'><i class="fa fa-check"></i> Sudah terunggah</a>
              @else
                <a href="#" class="btn btn-success disabled"><i class="fa fa-close"></i> Belum terunggah</a>
              @endif
            </div>
          </div>

          <div class="row form-group">
            <label class="col-sm-3">Surat Pengalihan Hak atas Penemuan</label>
            <div class="col-sm-9">
              @if($paten->surat_pengalihan_hak_atas_penemuan != null)
                <a href="/download/paten/surat-pengalihan-hak-penemuan/{{$paten->surat_pengalihan_hak_atas_penemuan}}" class="btn btn-success" target="_blank"><i class="fa fa-check" target='_blank'></i> Sudah terunggah</a>
              @else
                <a href="#" class="btn btn-success disabled"><i class="fa fa-close"></i> Belum terunggah</a>
              @endif
            </div>
          </div>

          <div class="row form-group">
            <label class="col-sm-3">Surat Kepemilikan Invensi oleh Inventor</label>
            <div class="col-sm-9">
              @if($paten->surat_kepemilikan_invensi_oleh_inventor != null)
                <a href="/download/paten/surat-kepemilikan-inventor/{{$paten->surat_kepemilikan_invensi_oleh_inventor}}" class="btn btn-success" target="_blank"><i class="fa fa-check"></i> Sudah terunggah</a>
              @else
                <a href="#" class="btn btn-success disabled"><i class="fa fa-close"></i> Belum terunggah</a>
              @endif
            </div>
          </div>

          <div class="row form-group">
            <label class="col-sm-3">Surat Kepemilikan Invensi oleh Lembaga</label>
            <div class="col-sm-9">
              @if($paten->surat_pernyataan_invensi_oleh_lembaga != null)
                <a href="/download/paten/surat-pernyataan-invensi-oleh-lembaga/{{$paten->surat_pernyataan_invensi_oleh_lembaga}}" class="btn btn-success" target='_blank'><i class="fa fa-check"></i> Sudah terunggah</a>
              @else
                <a href="#" class="btn btn-success disabled"><i class="fa fa-close"></i> Belum terunggah</a>
              @endif
            </div>
          </div>

          <div class="row form-group">
            <label class="col-sm-3">Dokumen Prioritas Terjemahan</label>
            <div class="col-sm-9">
              @if($paten->dokumen_prioritas_terjemahan != null)
                <a href="/download/paten/dokumen-terjemahan/{{$paten->dokumen_prioritas_terjemahan}}" class="btn btn-success" target='_blank'><i class="fa fa-check" ></i> Sudah terunggah</a>
              @else
                <a href="#" class="btn btn-success disabled"><i class="fa fa-close"></i> Belum terunggah</a>
              @endif
            </div>
          </div>
        </div>
      </div>
      <div  class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Lampiran Dokumen Subtantif</h3>
        </div>
        <div class='box-body'>
          <div class="row form-group">
            <label class="col-sm-3">File Uraian</label>
            <div class="col-sm-9">
              @if($paten->dokumen_subtantif_deskripsi->count() > 0)
                <a href="/download/paten/dokumen-subtantif-deskripsi/{{$paten->dokumen_subtantif_deskripsi[0]->nama_file}}" class="btn btn-success" target="_blank"><i class="fa fa-check"></i> Sudah terunggah</a>
              @else
                <a href="#" class="btn btn-success disabled"><i class="fa fa-close"></i> Belum terunggah</a>  
              @endif
            </div>
          </div>

          <div class="row form-group">
            <label class="col-sm-3">File Gambar</label>
            <div class="col-sm-9">
              @if($paten->dokumen_subtantif_gambar->count() > 0)
                <a href="/download/paten/dokumen-subtantif-gambar/{{$paten->dokumen_subtantif_gambar[0]->nama_file}}" class="btn btn-success" target="_blank"><i class="fa fa-check"></i> Sudah terunggah</a>
              @else
                <a href="#" class="btn btn-success disabled"><i class="fa fa-close"></i> Belum terunggah</a>
              @endif
            </div>
          </div>
        </div>
      </div>

    {{-- Box Validasi --}}
    <div class="box box-success">
      <div class="box-header with-border">
        <h3 class="box-title">Verifikasi</h3>
      </div>
      <div class="box-body">
        <p>Cek kembali kelengkapan data dan lampiran pengajuan Hak Paten. Jika data sudah lengkap dan benar, silahkan klik tombol verifikasi</p>
        <a href="{{ route('admin.paten.edit', $paten->id) }}" class="btn btn-success"><i class="fa fa-check"></i> Verifikasi</a>
      </div>
    </div>

  {{-- End of Content --}}
  </div>


@endsection

resources/views/admin/berita/edit.blade.php
@extends('layouts.adminLayout')

@section('content')
  <div class="content-header">
    
  </div>
  <div class="content">

    {{--  Boox Data Diri --}}
    <div class="box box-primary">
      <div class="box-header">
        <h3 class="box-title">Edit Berita</h3>
      </div>
      <div class="box-body">
        
      {{ Form::model($berita, ['route' => ['admin.berita.update', $berita->id], 'class' => 'form-horizontal', 'method'=>'PATCH', 'id'=>'frm-edit', 'enctype' => 'multipart/form-data']) }}
       <div class="modal-body">
        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-left" for="form-field-1-1"> Judul Berita : </label>
          <div class="col-sm-9">
            <input autofocus type="text" name="judul_berita" placeholder="Judul Berita" class="form-control" required value="{{ $berita->judul_berita }}"  />
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-left" for="form-field-1-1"> Isi Berita : </label>
          <div class="col-sm-9">
            <textarea name="isi_berita" cols="30" rows="10" required class="form-control" placeholder="Isi Berita">{{ $berita->isi_berita }}</textarea>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-2 control-label no-padding-left" for="form-field-1-1"> Ganti Foto : </label>
          <div class="col-sm-9">
            <img src="{{ asset('berita/'.$berita->foto) }}" width="130px">
            <input type="file" name="foto" class="form-control"  />
            <input type="hidden" name="foto_lama" value="{{ $berita->foto }}">
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn btn-sm btn-primary" type="submit">
          <i class="ace-icon fa fa-save"></i>
          Simpan
        </button>
        <a href="{{ route('admin.berita.index') }}">
        <button class="btn btn-sm btn-danger pull-right" type="button">
          <i class="ace-icon fa fa-times"></i>
          Kembali
        </button>
        </a>
      </div>
      {{ Form::close() }}

      </div>
    </div>

  {{-- End of Content --}}
  </div>


@endsection

resources/views/admin/berita/index.blade.php
@extends('layouts.adminLayout')

@section('header')
  <link rel="stylesheet" href="{{ asset('/css/dataTables.bootstrap.min.css') }}" media="screen" title="no title">
@endsection

@section('content')
  <div class="content-header">
    <h3>Berita</h3>
  </div>
  <div class="content body">
    <div class="row">
      <div class="col-xs-12">
        <div class="box box-success">
          <div class="clearfix">
          <br>
          <div class="pull-right tableTools-container">
            <a href="{{ route('admin.berita.create') }}" role="button">
              <button class="btn btn-sm btn-primary" >
                <i class="fa fa-plus"></i>
                Tambah Berita
              </button>
            </a>
          </div>
        </div>
          <div class="box-body">
            <table id="tableindustri" class="table table-bordered">
              <thead>
                <tr>
                  <th>No.</th>
                  <th>Judul</th>
                  <th>Foto</th>
                  <th></th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 1; ?>
                @foreach($beritas as $berita)
                  <tr>
                    <td>{{ $i++ }}</td>
                    <td>{{ $berita->judul_berita }}</td>
                    <td>
                      <img src="{{ asset('foto_berita/'.$berita->foto) }}" width="40px">
                    </td>
                    <td>
                      <a data-id="1" href="{{Route('admin.berita.edit', $berita->id)}}" class="btn-view btn bg-green"><i class="fa fa-pencil"></i></a>
                      </td>
                    <td>
                      {{ Form::model($berita, ['route' => ['admin.berita.destroy', $berita->id], 'method'=>'DELETE', 'class' => 'form-inline', 'id' => 'form-hapus-'.$i]) }}
                      <a href="#" class="btn-delete btn bg-red" onclick="confirmHapus('{{ $i }}','{{ $berita->judul_berita }}')"><i class="fa fa-trash"></i></a>
                      {{ Form::close() }}
                    </td>
                  </tr>
                @endforeach
                </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection

@section('js')
  <script src="{{ asset('/js/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('/js/bootbox.min.js') }}"></script>
  <script type="text/javascript">
    $('#tableindustri').dataTable();

    function confirmHapus(id,data) {
    // return false;
    bootbox.confirm("Hapus Berita '" + data + "' ?", function(result) {
      if(result) {
        document.getElementById('form-hapus-'+id).submit();
      }
    });         
  }
  </script>
@endsection